"""Initial migration

Revision ID: dbf6a7a13f7b
Revises: 
Create Date: 2024-12-23 14:55:43.953282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf6a7a13f7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_range', sa.String(length=50), nullable=False),
    sa.Column('shift_8_5', sa.String(length=200), nullable=True),
    sa.Column('shift_5_8', sa.String(length=200), nullable=True),
    sa.Column('shift_8_8', sa.String(length=200), nullable=True),
    sa.Column('night_off', sa.String(length=200), nullable=True),
    sa.Column('date_generated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start', sa.String(length=5), nullable=False),
    sa.Column('end', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('shift')
    op.drop_table('rota')
    # ### end Alembic commands ###
